apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: ksqldb-cli
  name: ksqldb-cli
  namespace: kafka

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksqldb-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/confluent-all-in-one-default: "true"
        io.kompose.service: ksqldb-cli
    spec:
      containers:
        - command:
            - /bin/sh
          image: confluentinc/cp-ksqldb-cli:7.5.0
          name: ksqldb-cli
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
