apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: mssql
  labels:
    app: mssql
spec:
  replicas: 1  # Número de instâncias do Pod
  selector:
    matchLabels:
      app: mssql  # Esta etiqueta deve corresponder à etiqueta dos Pods gerenciados pelo Deployment
  template:
    metadata:
      labels:
        app: mssql  # Etiqueta do Pod, utilizada pelo selector do Deployment
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Passw0rd!
        - name: MSSQL_PID
          value: developer
        ports:
        - containerPort: 1433
          name: mssql
        # Opções descomentadas para configurar limites de recursos
        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: "1Gi"